# Generated by Django 3.2.3 on 2021-06-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_2', '0002_auto_20210607_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='title',
        ),
    ]
